# Manejo de excepciones
# - TRY: En el try se coloca código que esperamos que pueda lanzar algún error.
# - EXCEPT: En el except se maneja el error, es decir, si ocurre un error dentro del bloque
#   de código del try, se deja de ejecutar el código del try y se ejecuta lo que
#   se haya definido en el Except.
# - ELSE: El else se ejecuta sólo si no hubo ninguna excepción lanzada desde el try
# - FINALLY: Se ejecuta SIEMPRE, haya sido lanzada la excepción o no haya sido lanzada.

try:
    pass
except Exception:
    print("Ocurrio una excepción")
else:
    print("No ocurrió ninguna excepción")
finally:
    print("Siempre me ejecuto")